# 第2章 Pythonの基本

## 2.1 四則演算

In [ ]:
1 + 2

3

In [ ]:
(1 + 2 * 3 - 4) / 5

0.6

In [ ]:
2 ** 8

256

## 2.2 変数

In [ ]:
x = 1
y = 1 / 3
x + y

1.3333333333333333

In [ ]:
data_1 = 1 / 5
data_2 = 3 / 5
data_1 + data_2

0.8

## 2.3 型

In [ ]:
type(100)

int

In [ ]:
type(100.1)

float

In [ ]:
x = 100
type(x)

int

In [ ]:
x = 100.1
type(x)

float

In [ ]:
x = "string"
type(x)

str

## 2.4 print文 

Jupyter Notebookでは変数名を表示するだけでその内容が表示されるが、セル内の最後の行でなければ表示されない。

In [ ]:
x = 1 / 3
x

y = 2 / 3
y

0.6666666666666666

In [ ]:
x = 1 / 3
print(x)

y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


In [ ]:
print('x = ' + str(x))

x = 0.3333333333333333


In [ ]:
print(f'weight = {x} kg')

weight = 0.3333333333333333 kg


In [ ]:
x = 1 / 3
y = 1 / 7
z = 1 / 4
print(f'weight: {x} kg, {y} kg, {z} kg')

weight: 0.3333333333333333 kg, 0.14285714285714285 kg, 0.25 kg


{数値:.nf}とすれば、小数点以下2桁までの表示となる

In [ ]:
print(f'weight: {x:.2f} kg, {y:.2f} kg, {z:.2f} kg')

weight: 0.33 kg, 0.14 kg, 0.25 kg


## 2.5 list（リスト、配列変数）

In [ ]:
x = [1, 1, 2, 3, 5]
print(x)

[1, 1, 2, 3, 5]


In [ ]:
x[0]

1

In [ ]:
x[2]

2

In [ ]:
print(type(x))
print(type(x[0]))

<class 'list'>
<class 'int'>


In [ ]:
s = ['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [ ]:
x = [1, 1, 2, 3, 5]
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [ ]:
x = [1, 1, 2, 3, 5]
len(x)

5

In [ ]:
a = [
    [1, 2, 3],
    [4, 5, 6]
]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
a = [
    [1, 2, 3],
    [4, 5, 6]
]
print(a[0][1])

2


連続した整数の配列を作るには、range(はじめの数, 終わりの数+1)を使う

In [ ]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


`y`はlist型に似ているが少し違い、range型と呼ばれるメモリを節約した形のデータ型である

In [ ]:
print(y)

range(5, 10)


range型はlist型と同様な方法で要素を参照できるが、要素を書き換えることはできない。  
例えば、range型に対して`y[2] = 2`とするとエラーが出る。

In [ ]:
z = list(range(5, 10))
print(z)

[5, 6, 7, 8, 9]


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 2.6 tuple（タプル）

In [ ]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


In [ ]:
a[1]

2

関数の出力が複数ある場合に1つの変数で受け取ると、自動的にtupleとしてまとめられる。  
既存の関数の入力がtupleで指定されている場合もある。

In [ ]:
type(a)

tuple

長さが1のtupleは`(1,)`と","を付ける。  
`(1)`とした場合、演算の順序を表す普通の括弧としてみなされる。

In [ ]:
a = (1)
type(a)

int

In [ ]:
a = (1,)
type(a)

tuple

## 2.7 if文

In [ ]:
x = 11
if x > 10:
    print('x is larger than 10.')
else:
    print('x is smaller than 11')

x is larger than 10.


In [ ]:
x > 10

True

In [ ]:
type(x > 10)

bool

In [ ]:
x = 15
if 10 < x and x < 20:
    print('x is between 10 and 20.')

x is between 10 and 20.


Pythonでは以下のような書き方もできる。

In [ ]:
x = 15
if 10 < x < 20:
    print('x is between 10 and 20.')

x is between 10 and 20.


## 2.8 for文

In [ ]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [ ]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)):
    num[i] *= 2
print(num)

[4, 8, 12, 16, 20]


In [ ]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


## 2.9 ベクトル

In [ ]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

list型はベクトルとして使用できない。  
Pythonでベクトルや行列を表すにはNumpyというライブラリを読み込んで機能を拡張する。

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2])
x

array([1, 2])

`x`を`print(x)`で表示させると、要素間の","が省略される。  
list型の場合には要素間に","が表示される。

In [ ]:
print(x)

[1 2]


In [ ]:
x = np.array([1, 2])
y = np.array([3, 4])
print(x + y)

[4 6]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x = np.array([1, 2])
print(x[0])

1


In [ ]:
x = np.array([1, 2])
x[0] = 100
print(x)

[100   2]


In [ ]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.arange(5, 10))

[5 6 7 8 9]


ndarray型の中身をコピーするには、通常の変数のように`b = a`ではなく、`b = a.copy()`としないといけない。  
単に`b = a`とすると、aの内容の保存先の参照が渡される。`b = a`とした後で`b`の内容を変更すると、その変更が`a`にも反映される。

In [ ]:
a = np.array([1, 1])
b = a
print('a = ' + str(a))
print('b = ' + str(b))

b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [100   1]
b = [100   1]


In [ ]:
a = np.array([1, 1])
b = a.copy()
print('a = ' + str(a))
print('b = ' + str(b))

b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [1 1]
b = [100   1]


ndarray型だけでなく、list型でも同様の現象が起きる。  
list型の場合には`import copy`としてから、`a = copy.deepcopy()`とすることでコピーできる。

In [ ]:
a = [1, 1]
b = a
print('a = ' + str(a))
print('b = ' + str(b))

b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1, 1]
b = [1, 1]
a = [100, 1]
b = [100, 1]


In [ ]:
import copy

a = [1, 1]
b = copy.deepcopy(a)
print('a = ' + str(a))
print('b = ' + str(b))

b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1, 1]
b = [1, 1]
a = [1, 1]
b = [100, 1]


## 2.10 行列

行列はndarrayの二次元配列として定義できる。

In [ ]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(x)

[[1 2 3]
 [4 5 6]]


行列のサイズ

In [ ]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
x.shape

(2, 3)

In [ ]:
type(x.shape)

tuple

In [ ]:
h, w = x.shape
print(h)
print(w)

2
3


要素の参照は次元ごとに","で区切って表す。インデックスは0からは始まる。

In [ ]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
x[1, 2]

6

In [ ]:
# こちらの書き方でも要素を参照できる。
x[1][2]

6

要素の書き換え

In [ ]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


要素が0や1のndarrayの作成

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((2, 10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
x = np.ones((2, 10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


要素がランダムな行列の生成

In [ ]:
# np.random.rand(size) は各要素を0～1の一様分布から生成した行列を生成する。
# sizeはtupleではないことんい注意。np.random.rand((2, 3)) とするとエラーになる。
np.random.rand(2, 3)

array([[0.34686994, 0.19154672, 0.34435764],
       [0.91296276, 0.69459521, 0.03453048]])

In [ ]:
# np.random.randn(size) を使うと平均0、分散1のガウス分布（標準正規分布）からの乱数が生成できる。
np.random.randn(2, 3)

array([[ 0.62807648,  1.3855904 , -1.66638532],
       [ 0.376031  , -0.11573787, -0.71685856]])

In [ ]:
# np.random.randint(low, high, size) を使うと low から high-1 までの整数値からなる size の大きさの行列を生成できる。
np.random.randint(5, 10, (2, 3))

array([[5, 5, 6],
       [6, 8, 6]])

## 2.11 行列（ndarray）の四則演算

行列における四則演算

In [ ]:
x = np.array([
    [4, 4, 4],
    [8, 8, 8]
])
y = np.array([
    [1, 1, 1],
    [2, 2, 2]
])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


スカラー × 行列

In [ ]:
x = np.array([
    [4, 4, 4],
    [8, 8, 8]
])
print(10 * x)

[[40 40 40]
 [80 80 80]]


算術関数

In [ ]:
# 平方根
x = np.array([
    [4, 4, 4],
    [9, 9, 9]
])
print(np.sqrt(x))

[[2. 2. 2.]
 [3. 3. 3.]]


In [ ]:
# 指数関数
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.exp(x))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [ ]:
# 対数関数
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.log(x))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [ ]:
# 四捨五入
x = np.array([
    [1.5, 2.6, 3.2],
    [4.4, 5.1, 6.9]
])
print(np.round(x))

[[2. 3. 3.]
 [4. 5. 7.]]


In [ ]:
# 平均
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.mean(x))

3.5


In [ ]:
# 標準偏差
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.std(x))

1.707825127659933


In [ ]:
# 最大値
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.max(x))

6


In [ ]:
# 最小値
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(np.min(x))

1


行列積

In [ ]:
v = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
w = np.array([
    [1, 1],
    [2, 2],
    [3, 3]
])
print(v.dot(w))

[[14 14]
 [32 32]]


In [ ]:
print(w.dot(v))

[[ 5  7  9]
 [10 14 18]
 [15 21 27]]


## 2.12 スライシング

In [ ]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [ ]:
print(x[5:])

[5 6 7 8 9]


In [ ]:
print(x[3:8])

[3 4 5 6 7]


In [ ]:
print(x[3:8:2])

[3 5 7]


In [ ]:
# 配列の順番を逆向きにする
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# スライシングは1次元以上のndarrayでも使える
y = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


## 2.13 条件を満たすデータの書き換え

bool配列の利用

In [ ]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [ ]:
x[x > 3]

array([ 5,  8, 13])

In [ ]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


## 2.14 Help

`help(func)`で関数の説明文を出力できる

In [ ]:
import numpy as np
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

## 2.15 関数

In [ ]:
# 関数の定義
def my_func1():
    print('Hi!')

# 関数の実行
my_func1()

Hi!


In [ ]:
# 関数の定義
def my_func2(a, b):
    c = a + b
    return c

# 関数の実行
my_func2(1, 2)

3

In [ ]:
# 平均値と標準偏差を戻り値とする関数を定義
def my_func3(d):
    m = np.mean(d)
    s = np.std(d)
    return m, s

# 標準正規分布から100個の乱数を生成
data = np.random.randn(100)

# 生成された乱数の平均と標準偏差を取得・出力
data_mean, data_std = my_func3(data)
print(f'mean: {data_mean:.2f}, std: {data_std:.2f}')

mean: -0.03, std: 1.10


In [ ]:
# 戻り値が複数でも1つの変数で受け取ることができる
output = my_func3(data)
print(output)
print(type(output))
print(f'mean: {output[0]:.2f}, std: {output[1]:.2f}')

(-0.031270694108076445, 1.098730470666293)
<class 'tuple'>
mean: -0.03, std: 1.10


## 2.16 ファイル保存

1つのndarray型の保存

In [ ]:
# データの準備
data = np.array([1, 1, 2, 3, 5, 8, 13])
print(data)

[ 1  1  2  3  5  8 13]


In [ ]:
# ファイルの保存
np.save('datafile.npy', data)

In [ ]:
# データの消去
data = []
print(data)

[]


In [ ]:
# ファイル読み出し
data = np.load('datafile.npy')
print(data)

[ 1  1  2  3  5  8 13]


複数のndarray型の保存

In [ ]:
# データの準備
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])

In [ ]:
# ファイル保存
np.savez('datafile2.npz', data1=data1, data2=data2)

In [92]:
# データ消去
data1 = []
data2 = []

In [93]:
# ファイル読み出し
outfile = np.load('datafile2.npz')
print(outfile)

In [95]:
# 格納している全データの表示
print(outfile.files)

['data1', 'data2']


In [96]:
# データの取り出し
data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)

[1 2 3]
[10 20 30]
